slam_toolbox:
  ros__parameters:
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: scan

    use_sim_time: false
    use_map_saver: true
    scan_queue_size: 5
    transform_publish_period: 0.02
    map_update_interval: 2.5
    resolution: 0.03
    min_laser_range: 0.2
    max_laser_range: 2.0
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    minimum_travel_distance: 0.15
    minimum_travel_heading: 0.15
    throttle_scans: 2 # lower to 1 if CPU allows it
    do_loop_closing: true
    use_scan_matching: true
    use_scan_barycenter: true
